In [41]:
from pandas import Series, DataFrame
import pandas as pd
import numpy as np

sdata ={'Ohio':35000, 'Texas':71000, 'Oregon':16000,'Utah':5000}
obj3 = Series(sdata)
obj3
states = ['California','Ohio','Texas','Oregon']
obj4 = Series(sdata, index=states)
obj4
pd.isnull(obj4)
pd.notnull(obj4)
obj4.isnull()
obj4 + obj3
obj4.name = 'population'
obj4.index.name = 'state'
obj4
obj4.index = ['Bob','Steve','Jeff','Ryan']
obj4.index.name = 'name'
obj4


#---------------------DataFrame-----------------
data = {
    'state':['Ohio','Ohio','Ohio','Nevada','Nevada'],
    'year':[2000,2001,2002,2003,2004],
    'pop':[1.5,1.7,3.6,2.4,2.9]
}
frame = DataFrame(data)
frame
DataFrame(data,columns=['year','state','pop'])
frame2 =  DataFrame(data,columns=['year','state','pop','debt'],index=['one','two','three','four','five']
                    )
frame2
frame2.columns
frame2.year
frame2._ixs(0,axis=0) #----0纵1横，（取纵坐标索引）
frame2['debt'] = 16.5
frame2
frame2['debt'] = np.arange(5,10)
frame2
frame2['eastern'] = frame2.state == 'Ohio'
series = frame2.state == 'Ohio'
series
frame2.values


#----------------reindex--------------
obj3 = Series(['blue','purple','yellow'],index=[0,2,4])
obj3.reindex(range(6),method='ffill')
obj3.reindex(range(6),method='bfill')


#------------pandas的算术运算和数据对齐-------------
df1 = DataFrame(np.arange(0,12).reshape((3,4)),columns=list('abcd'))
df2 = DataFrame(np.arange(20.).reshape((4,5)),columns=list('abcde'))
df1
df2
df1 + df2
df1.add(df2, fill_value = 0)


#-------------DataFrame与Series之间的运算--------------
arr = np.arange(12).reshape(3,4)
arr[0]
arr - arr[0]

frame = DataFrame(np.arange(12).reshape(4,3),columns=list('bde'),index=['Utah',
                                                                        'Ohio',
                                                                        'Texas',
                                                                        'Oregon'])
frame
series = frame._ixs(0,axis=0)
series
frame - series
series2 = Series(range(3),index=list('bef'))
series2
frame + series2
series3 = frame['d']
series3
frame.sub(series3, axis = 0)


#-------------------函数的应用与映射----------------
frame = DataFrame(np.random.randn(4,3),columns=list('bde'),index=['Utah',
                                                                        'Ohio',
                                                                        'Texas',
                                                                        'Oregon'])
frame
np.fabs(frame)
f = lambda x:x.max() - x.min()
frame.apply(f)
frame.apply(f,axis=1)
def f(x):
    return Series([x.min(),x.max()],index=['min','max'])
frame.apply(f)
frame.apply(f,axis=1)
format = lambda x:'%.2f' %x
frame.applymap(lambda x: '%.2f' %x)
frame.applymap(format)
frame.e.map(format)



#-----------------排序和排名----------------
obj = Series(range(4),index=list('dabc'))
obj.sort_index()
frame = DataFrame(np.arange(8).reshape((2,4)),columns=list('dabc'),index=['three',
                                                                        'one'])
frame
frame.sort_index()
frame.sort_index(axis=1)
frame.sort_index(axis=1,ascending=False)
obj
obj = Series([4,7,-3,2])
obj.sort_values()  #--书中是obj.order()但是我没找到
frame
frame.sort_values(by=['a'],ascending=False)


#---------------汇总和计算描述------------
frame.sum()
frame.describe()


#-------------唯一值，值计数以及成员资格-----------
obj = Series(['c','a','d','a','a','b','b','c','c'])
uniques = obj.unique()
uniques
obj.value_counts()
uniques.sort()
uniques
s = pd.value_counts(obj.values, sort=True)
s.sort_index()
data = DataFrame({'Qu1':[1,3,4,3,4],
                  'Qu2':[2,3,1,2,6],
                  'Qu3':[1,5,2,4,4]})
data
result = data.apply(pd.value_counts)
result
result = data.apply(pd.value_counts).fillna(0)
result


#------------------处理缺失数据------------------
string_data = Series(['aardvarl','artichoke',np.nan,'avocado'])
string_data
string_data.isnull()
string_data[0] = None
string_data.isnull()
string_data.dropna()
string_data.notnull()
string_data[string_data.notnull()]
df = DataFrame(np.random.randn(7,3))
for i in range(5):
    df._ixs(i,axis=0)[1] = np.nan
for i in range(3):
    df._ixs(i,axis=0)[2] = np.nan
df
df.dropna(thresh=3)
df.fillna(0.0)
#-------------------填充缺失数据
df.fillna({1:0.5255,2:-1})
df.fillna(method='bfill',limit=3,inplace=True)
df
frame['d']
data = Series(np.random.randn(10),
              index=[
                  ['a','a','a','b','b','b','c','c','d','d'],
                  [1,2,3,1,2,3,1,2,2,3]   
                     ])
data
data.index
data['b']
data['b':'d']
data[['b','d']]
data[:,1]
data.unstack()
frame = DataFrame(np.arange(12).reshape((4,3)),
                  index=[['a','a','b','b'],[1,2,1,2]],
                  columns=[['Ohio','Ohio','Colorado'],['Green','Red','Green']])
frame
frame.index.names = ['key1','key2']
frame.columns.names=['State','color']
frame.index.names
frame.swaplevel('key1','key2')
frame
frame.sort_index()
frame.swaplevel('key1','key2')
frame.sum(level='color',axis=1)


#--------------使用DataFrame的列----------------
frame = DataFrame({'a':range(7),'b':range(7,0,-1),
                   'c':['one','one','one','three','three','three','three',],
                   'd':[0,1,2,0,1,2,3]})
frame
a = frame.set_index(['c','d'])
frame2.set_index(['debt','eastern'],drop=False)
frame.reset_index()
a.reset_index()

       c  d  a  b
0    one  0  0  7
1    one  1  1  6
2    one  2  2  5
3  three  0  3  4
4  three  1  4  3
5  three  2  5  2
6  three  3  6  1